exclude = [
	'^file:',
	'https://github.com/kitschpatrol/yanki-obsidian/releases/latest',
	'https://obsidian\.md/help/links#Link\+to\+a\+block\+in\+a\+note',
	'https://obsidian\.md/help/links#Link\+to\+a\+heading\+in\+a\+note',
]
