onlyBuiltDependencies:
  - electron
  - esbuild
  - obsidian-typings
  - oxc-resolver
  - puppeteer
  - unrs-resolver
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
