publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  electron: true
  esbuild: true
  obsidian-typings: false
  oxc-resolver: true
  puppeteer: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@kitschpatrol/*'
  - yanki-connect@4.0.10
  - yanki@2.0.15
